- name: Ensure keepalived service is stopped
  service:
    name: keepalived
    state: stopped
  register: result
  failed_when:
    - result.failed == true
    - '"Could not find the requested service" not in result.msg'