version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - homarr
      - ha
  
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./tools/homarr/configs:/app/data/configs
      - ./tools/homarr/icons:/app/public/icons
      - ./tools/homarr/data:/data
    ports:
      - '7575:7575'
    expose:
      - '7575'

  ha:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    build:
      dockerfile: docker/Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ./tools/ha/config:/config
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Europe/Kiev
    ports:
      - '8123:8123'

  speedtest:
    image: robinmanuelthiel/speedtest:0.1.1
    restart: always
    depends_on:
      - influxdb
    environment:
      - LOOP=true
      - LOOP_DELAY=3600 # Once per hour
      - DB_SAVE=true
      - DB_HOST=http://influxdb:8086
      - DB_NAME=speedtest
      - DB_USERNAME=admin
      - DB_PASSWORD=adminpass
      
  # Creates an InfluxDB instance to store the
  # speed test results
  influxdb:
    image: influxdb:1.8.10
    restart: always
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpass
      - INFLUXDB_DB=speedtest
      
  # Displays the results in a Grafana dashborad
  grafana:
    image: grafana/grafana:latest
    restart: always
    user: "1000"
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana:/var/lib/grafana
  
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./tools/mqtt/config:/mosquitto/config:rw
      - ./tools/mqtt/data:/mosquitto/data:rw
      - ./tools/mqtt/log:/mosquitto/log:rw
    restart: unless-stopped

  plex:
    image: greensheep/plex-server-docker-rpi:latest
    container_name: plex
    restart: unless-stopped
    env_file:
      - ./tools/plex/.env
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ./volumes/plex/database:/config
      - ./volumes/plex/transcode:/transcode
      - ./volumes/media:/data

  deluge:
    image: jordancrawford/rpi-deluge
    container_name: deluge
    user: "1000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /volumes/deluge/config:/config
      - /volumes/media:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped
