version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - homarr
      - ha
  
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./tools/homarr/configs:/app/data/configs
      - ./tools/homarr/icons:/app/public/icons
      - ./tools/homarr/data:/data
    ports:
      - '7575:7575'
    expose:
      - '7575'

  ha:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - ./tools/ha/config:/config
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Europe/Kiev
    ports:
      - '8123:8123'