- name: Install dependencies
  apt:
    force_apt_get: yes
    name:
      - gnupg2
      - software-properties-common

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/raspbian {{ ansible_distribution_release }} stable
    filename: docker

- name: Install Docker
  apt:
    force_apt_get: yes
    name:
      - docker-ce:armhf
      - python3-setuptools
      - python3-pip

    install_recommends: no

- name: Install Docker SDK for python
  apt:
    force_apt_get: yes
    name: 
      - python3-docker
      - docker-compose
    install_recommends: no

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker

- name: Enable Docker IPv6
  copy:
    dest: /etc/docker/daemon.json
    mode: 0600
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64"
      }
  notify: Restart Docker

- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta:
    reset_connection

- name: Flush handlers
  meta: flush_handlers